# A l'état d'ébauche ... idée customisé la config d'ElasticSearch:
# fournir le fichier de config via un volume
# installer le plugin Marvel
FROM elasticsearch:latest
VOLUME /usr/share/elasticsearch/config

RUN /usr/share/elasticsearch/bin/plugin install elasticsearch/marvel/latest

VOLUME /usr/share/elasticsearch/config

RUN /usr/share/elasticsearch/bin/plugin install elasticsearch/marvel/latest


