# A l'état d'ébauche ... idée customisé la config d'ElasticSearch:
# fournir le fichier de config via un volume
# installer le plugin Marvel
FROM elasticsearch:2.2

RUN /usr/share/elasticsearch/bin/plugin install discovery-multicast
